"""create_sleep_entries_table

Revision ID: 07d76af3ce67
Revises: 
Create Date: 2025-05-23 17:25:48.603624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d76af3ce67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bedtime', sa.DateTime(), nullable=False),
    sa.Column('waketime', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('rem_minutes', sa.Integer(), nullable=False),
    sa.Column('deep_minutes', sa.Integer(), nullable=False),
    sa.Column('core_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_entries_id'), 'sleep_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleep_entries_id'), table_name='sleep_entries')
    op.drop_table('sleep_entries')
    # ### end Alembic commands ###
